Symbol Visibility in ROS on Windows
ms-iot/ROSOnWindows pull request #322
Opened 2021-03-15 21:00 UTC by lilustga

New Page under the Porting Folder which describes how to add explicit symbol visibility to a ROS package.

2021-03-15 22:36 UTC, ooeygui requested changes

2021-03-15 22:36 UTC, ooeygui commented on docs/Porting/SymbolVisibility.md
> +The two main solutions to this are adding visibility control headers and the WINDOWS_EXPORT_ALL_SYMBOLS property. It is recommended to use visibility control headers as they are more deterministic an
`Microsoft recommends ROS developers use visibility control headers to control the export of symbols from a binary.` `Visibility Headers provide more control over symbol export, and offer other benefits including smaller binary size and reduced link times.

2021-03-15 22:36 UTC, ooeygui commented on docs/Porting/SymbolVisibility.md
> +Open Robotics recommends using a deterministic method to ensure symbol visibility. This method is to use visibility control headers. The purpose of these headers is to define a macro for each library
Can we merge these two paragraphs?

2021-03-15 22:36 UTC, ooeygui commented on docs/Porting/SymbolVisibility.md
> +A `visibility_control.hpp` header like the one in the example below can be placed in the `includes` folder for each library with a unique macro name.
grammar. `is a header`

2021-03-15 22:36 UTC, ooeygui commented on docs/Porting/SymbolVisibility.md
> +This example shows how a visibility control header was added for the `robot_state` library within `movit_core`.
Instead of copying a header from another repo, perhaps use a generic name like `MY_CLASS` in order to maintain the chain of custody.

2021-03-15 22:36 UTC, ooeygui commented on docs/Porting/SymbolVisibility.md
> +CMake implements a macro which will export all symbols on Windows. The `WINDOWS_EXPORT_ALL_SYMBOLS` property turns all `add_library` calls which do not specify type to shared builds. Calls to `add_li
I'm not sure what the third sentence means.

2021-03-15 22:36 UTC, ooeygui commented on docs/Porting/SymbolVisibility.md
> +class KinematicsBase
Use generic class name.

2021-03-16 04:07 UTC, ooeygui approved these changes

2021-03-16 09:38 UTC, traversaro commented on docs/Porting/SymbolVisibility.md
> +#endif  // MY_LIB__VISIBILITY_CONTROL_HPP_
I may be missing something, but it seems that with this visibility control header, the code cannot be compiled/used as a static library?

2021-03-16 09:59 UTC, traversaro reviewed
Could it make sense to link this new documentation in https://github.com/ms-iot/ROSOnWindows/blob/872aae72c3d806fab46f300dc9484e55cdbf744e/docs/Porting/Cookbook.md#error-lnk2019-unresolved-external-symbol ?

2021-03-16 18:13 UTC, ooeygui commented
@lilustga Let's remove the section from the cookbook that @traversaro mentions above since we're elevating this to a top level link.

2021-03-16 18:15 UTC, ooeygui commented on docs/Porting/SymbolVisibility.md
> +#endif  // MY_LIB__VISIBILITY_CONTROL_HPP_
@lilustga can you comment on @traversaro's question? It would be good to capture this in the doc as well

2021-03-16 18:27 UTC, traversaro commented on docs/Porting/SymbolVisibility.md
> +#endif  // MY_LIB__VISIBILITY_CONTROL_HPP_
Related comment in an older PR: https://github.com/ros2/rclcpp/pull/638#discussion_r260511413 .

2021-03-16 21:44 UTC, lilustga commented on docs/Porting/SymbolVisibility.md
> +#endif  // MY_LIB__VISIBILITY_CONTROL_HPP_
@traversaro, I generated a header using generate_export_header and saw how it uses `LIB_NAME_STATIC_DEFINE` to not set the `TOOLS_EXPORT` macro to either dllimport or dllexport. We could add the same logic to this boilerplate header, would that be sufficient to allow for building the same lib as both static and shared?

2021-03-17 08:06 UTC, traversaro commented on docs/Porting/SymbolVisibility.md
> +#endif  // MY_LIB__VISIBILITY_CONTROL_HPP_
If you have a non-generate export header, if you add a `LIB_NAME_STATIC_DEFINE` to disable `dllimport`  and `dllexport`  decoration, you also need to specify that that symbol needs to be define when the library is a static library, i.e. : 
~~~
get_target_property(lib_name_TYPE lib_name TYPE)
if(lib_name_TYPE  STREQUAL "STATIC_LIBRARY")
  target_compile_definitions(lib_name PUBLIC LIB_NAME_STATIC_DEFINE)
endif()
~~~

Note that however this solution only works correctly in downstream projects that  link the static version of the library if the downstream projects link the library using CMake and linking with the exported target. If they do not use CMake or they do not link with the exported target, they need to define `LIB_NAME_STATIC_DEFINE` manually depending of whether they are linking the static version of lib_name or the shared one.

2021-03-17 19:12 UTC, lilustga commented on docs/Porting/SymbolVisibility.md
> +#endif  // MY_LIB__VISIBILITY_CONTROL_HPP_
Thanks for the insight, I'll test this in a future workstream and incorporate it into the documentation.

2021-03-18 23:54 UTC, ooeygui approved these changes

2021-03-18 23:54 UTC, merged